// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// Profile
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const STOP_LOADING = 'STOP_LOADING';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const RESET_PROFILE_REDUCER = 'RESET_PROFILE_REDUCER';
// Teachers
export const GET_TEACHERS = 'GET_TEACHERS';
export const ADD_TEACHER = 'ADD_TEACHER';
export const REMOVE_TEACHER = 'REMOVE_TEACHER';
export const UPDATE_TEACHER = 'UPDATE_TEACHER';
export const RESET_TEACHER_REDUCER = 'RESET_TEACHER_REDUCER';
// Subjects
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const REMOVE_SUBJECT = 'REMOVE_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const RESET_SUBJECT_REDUCER = 'RESET_SUBJECT_REDUCER';
// Semester
export const GET_ALL_SEMESTER = 'GET_ALL_SEMESTER';
export const ADD_SEMESTER = 'ADD_SEMESTER';
export const REMOVE_SEMESTER = 'REMOVE_SEMESTER';
export const UPDATE_SEMESTER = 'UPDATE_SEMESTER';
export const RESET_SEMESTER_REDUCER = 'RESET_SEMESTER_REDUCER';

export const ADD_COURSE = 'ADD_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
// Filter
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
// Routine
export const GET_ALL_ROUTINE_PERIOD = 'GET_ALL_ROUTINE_PERIOD';
export const ADD_ROUTINE_PERIOD = 'ADD_ROUTINE_PERIOD';
export const REMOVE_ROUTINE_PERIOD = 'REMOVE_ROUTINE_PERIOD';
export const UPDATE_ROUTINE_PERIOD = 'UPDATE_ROUTINE_PERIOD';
export const RESET_ROUTINE_PERIOD_REDUCER = 'RESET_ROUTINE_PERIOD_REDUCER';

export const ADD_CLASSES = 'ADD_CLASSES';
export const REMOVE_CLASSES = 'REMOVE_CLASSES';
export const UPDATE_CLASSES = 'UPDATE_CLASSES';

// Exams
export const GET_EXAMS = 'GET_EXAMS';
export const ADD_EXAM = 'ADD_EXAM';
export const REMOVE_EXAM = 'REMOVE_EXAM';
export const UPDATE_EXAM = 'UPDATE_EXAM';
export const RESET_EXAM_REDUCER = 'RESET_EXAM_REDUCER';
